# sql file for github patcher module


INSERT INTO `language_text` VALUES ('en', '_module','github_patcher','GitHub Based Patcher',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_module','github_patcher_text','This is github based patcher module.',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','path_to_git_exec','Path to Git Executable',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','new_branch_checkout','New Branch',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','checkout','Checkout',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','commit_message','Commit Message',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','commit','Commit',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','push','Push',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','step1_checkout','STEP 1: Checkout to a New Branch',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','step2_changes','STEP 2: Make Changes',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','step3_commit','STEP 3: Commit the Changes',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','step4_test','STEP 4: Test the Changes',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','step5_push','STEP 5: Push the Changes',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','step6_create','STEP 6: Create a Patch',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','github_username','GitHub Username',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','github_password','GitHub Password',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','pr_title','Title',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','pr_body','Body',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','select_files_to_add','Select Files to Add',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','git_username','Git Username',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','git_email','Git email',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','github_credentials','Github Credentials',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','input_new_branch','Input name of new branch to checkout',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','make_changes','Make Changes in files',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','commit_changes','Commit the made changes',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','test_changes','Test the Changes before making a Patch',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','push_changes','Push the Changes',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','create_pr','Create a patch to be available as a Pull Request on GitHub',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','git_executable_description','On most Unix system, it is "/usr/bin/git". On Windows, it may be "C:\\\\Program Files\\\\Git\\\\bin\\\\git.exe".',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','pr_status','Status',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','merged_at','Merged At',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','updated_at','Updated At',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','open_patches','Open Patches',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','closed_patches','Closed Patches',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','patch_test','Test Patch',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','patch_test_description','Test This Feature On A Separate Branch Before Installing (Recommended)',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','patch_test_branch','Testing Branch',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','uninstall_last_installed','Uninstall',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','install_selected','Install',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','install_label','Install the Selected Patch',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','uninstall_label','Uninstall the Last Patch Installed',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','last_patch_detail','Details of Last Installed Patch',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_template','PATCH_NOT_INSTALLED','Previously Installed Patch does not Exist',NOW(),'');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_GITHUB_PATCHER_GIT_EXE_EMPTY', 'Path to Git Executable Empty', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_GITHUB_PATCHER_GIT_USERNAME_EMPTY', 'Git Username Field Empty', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_GITHUB_PATCHER_GIT_EMAIL_EMPTY', 'Git E-mail Field Empty', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_INVALID_GIT_BINARY', 'Invalid Path to Git Executable', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_CANNOT_CHECKOUT', 'Cannot Checkout to Specified Branch', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_CANNOT_COMMIT', 'Unable to Commit', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_CANNOT_PUSH', 'Unable to Push', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_PR_FAILED', 'Creation of Patch/Pull Request Failed', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_UNABLE_TO_ADD_MOD', 'Unable to Add Modified File', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_UNABLE_TO_ADD_NEW', 'Unable to Add New File', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_UNABLE_TO_DELETE', 'Unable to Delete File', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_CANNOT_CONNECT_TO_GITHUB', 'Unable to Connect to GitHub', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_UNABLE_TO_INSTALL', 'Unable to Install', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_BRANCH_ALREADY_EXISTS', 'Branch With This Name Already Exists', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_UNABLE_TO_APPLY_TO_TEST_BRANCH', 'Unable to Apply Patch to Test Branch', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_UNABLE_TO_UNINSTALL', 'Unable to Uninstall', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_ERROR_PATCH_NOT_INSTALLED', 'Previously Installed Patch does not Exist', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_GITHUB_PATCHER_GIT_EXEC_SAVED', 'Path to Git Executable Saved', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_GITHUB_PATCHER_GIT_USERNAME_SAVED', 'Git Username Saved', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_GITHUB_PATCHER_GIT_EMAIL_SAVED', 'Git E-mail Saved', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_CHECKED_OUT', 'Checked-Out to New Branch Successfully', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_COMMITTED', 'Committed the Changes Successfully', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_PUSHED', 'Pushed the Changes Successfully', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_PR_SUCCESS', 'Patch Created Successfully', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_PATCH_APPLIED_TO_TEST_BRANCH', 'Patch Applied to Test Branch', NOW(), '');
INSERT INTO `language_text` VALUES ('en', '_msgs', 'AT_FEEDBACK_PATCH_UNINSTALLED_SUCCESSFULLY', 'Patch Uninstalled Successfully', NOW(), '');